# -*- coding: utf-8 -*-
#
# Tuleap documentation build configuration file, created by
# sphinx-quickstart on Thu Oct  4 21:33:56 2012.
#
# This file is execfile()d with the current directory set to its containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

from recommonmark.parser import CommonMarkParser

source_parsers = {'.md': CommonMarkParser}

source_suffix = ['.md']
master_doc = 'index'
