image:
  file: .gitpod.Dockerfile
tasks:
  - init: >
      nix-shell --command "npm ci && npm run build && make SPHINXOPTS=\"-D html_theme=tuleap_org\" watch-html"
ports:
  - port: 5000
    onOpen: open-preview
vscode:
  extensions:
    - bbenoist.Nix
    - lextudio.restructuredtext
    - trond-snekvik.simple-rst
    - ms-python.python
    - streetsidesoftware.code-spell-checker
