language: python

services:
  - docker

python:
    - "3.6"
    - "3.7"

install:
    - pip install -r requirements.txt

script:
    - make SPHINXOPTS='-W' html


jobs:
  include:
    - stage: "Verify build docs.tuleap.org"
      script: docker build -f docs.tuleap.org/Dockerfile -t test-build .